# Generated by Django 5.1.7 on 2025-03-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_uploadedimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
