# Generated by Django 5.1.7 on 2025-03-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_uploadedimage_description_uploadedimage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
